### ISSUE TITLE
Wrong content type in request message from Gp2Gp to MHS outbound adapter

### ISSUE THREAD

**Issue by no-man-is-an-island** [nhsconnect/integration-adaptor-gp2gp#94]
Gp2Gp adapter version: 0.0.2
MHS outbound adapter version: 1.0.2

Steps to reproduce:

When running the e2e tests, with the gp2gp adapter pointing at a real instance of the MHS adapter (as opposed to the mock). No spine/opentest connectivity needed, as the outbound request does not get past the initial request validation in the MHS outbound service.

Description of error:

The outbound MHS request sent by the Gp2Gp adapter gets rejected with the following error:

```
gp2gp_1     | 2021-02-18 08:51:46.053 Level=INFO  Logger=uk.nhs.adaptors.gp2gp.mhs.MhsClient ConversationId=1234 TaskId=859d0c11-eb5e-422c-b34c-7026466447c6 Thread="DefaultMessageListenerContainer-1" Message="Mhs Outbound Request, Mhs Outbound Endpoint: http://outbound"
outbound_1  | [2021-02-18T08:51:46.138562Z] | INFO | 8 |  | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 |  |  | outbound.outbound.request.synchronous.handler | Didn't receive message id in incoming request from supplier, so have generated a new one.
outbound_1  | [2021-02-18T08:51:46.139862Z] | INFO | 8 |  | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.outbound.request.synchronous.handler | Found correlation id on incoming request.
outbound_1  | [2021-02-18T08:51:46.140034Z] | INFO | 8 | RCMR_IN030000UK06 | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.outbound.request.synchronous.handler | Found Interaction-Id in message headers
outbound_1  | [2021-02-18T08:51:46.140383Z] | INFO | 8 | RCMR_IN030000UK06 | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.outbound.request.synchronous.handler | Outbound POST received. Request="HTTPServerRequest(protocol='http', host='outbound', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.240.10')"
outbound_1  | [2021-02-18T08:51:46.140568Z] | ERROR | 8 | RCMR_IN030000UK06 | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.outbound.request.synchronous.handler | Unsupported content type in request. ExpectedContentType=application/json ActualContentType=text/plain;charset=UTF-8
outbound_1  | [2021-02-18T08:51:46.141053Z] | INFO | 8 | RCMR_IN030000UK06 | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.utilities.timing | FuncName=post from Handler=SynchronousHandler took Duration=0.004 seconds
outbound_1  | [2021-02-18T08:51:46.141299Z] | WARNING | 8 | RCMR_IN030000UK06 | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.tornado.general | 415 POST / (192.168.240.10): Unsupported content type. Only application/json request bodies are supported.
outbound_1  | [2021-02-18T08:51:46.144080Z] | WARNING | 8 | RCMR_IN030000UK06 | 36E3BB72-DDD4-4AB8-9FEC-4037BE71BDE8 | 1234 |  | outbound.tornado.access | 415 POST / (192.168.240.10) 13.00ms
gp2gp_1     | 2021-02-18 08:51:46.166 Level=ERROR Logger=u.n.a.gp2gp.common.task.TaskConsumer ConversationId=1234 TaskId=859d0c11-eb5e-422c-b34c-7026466447c6 Thread="DefaultMessageListenerContainer-1" Message="Error while processing task queue message ID:796f12f7-46e2-4ac1-917d-6711c983d992:2:1:2-1"
gp2gp_1     | uk.nhs.adaptors.gp2gp.mhs.InvalidOutboundMessageException: The following error occurred during Mhs Outbound Request: 415: Unsupported content type. Only application/json request bodies are supported.
gp2gp_1     | 	at uk.nhs.adaptors.gp2gp.common.service.WebClientFilterService.lambda$getResponseError$4(WebClientFilterService.java:52)
gp2gp_1     | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
gp2gp_1     | Error has been observed at the following site(s):
gp2gp_1     | 	|_ checkpoint ⇢ Request to POST http://outbound [DefaultWebClient]
gp2gp_1     | Stack trace:
gp2gp_1     | 		at uk.nhs.adaptors.gp2gp.common.service.WebClientFilterService.lambda$getResponseError$4(WebClientFilterService.java:52)
gp2gp_1     | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
gp2gp_1     | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
gp2gp_1     | 		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
gp2gp_1     | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:295)
gp2gp_1     | 		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
gp2gp_1     | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1789)
gp2gp_1     | 		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
gp2gp_1     | 		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
gp2gp_1     | 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
gp2gp_1     | 		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
gp2gp_1     | 		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:389)
gp2gp_1     | 		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:396)
gp2gp_1     | 		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:452)
gp2gp_1     | 		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:664)
gp2gp_1     | 		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
gp2gp_1     | 		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
gp2gp_1     | 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
gp2gp_1     | 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
gp2gp_1     | 		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
gp2gp_1     | 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
gp2gp_1     | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
gp2gp_1     | 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
gp2gp_1     | 		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
gp2gp_1     | 		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
gp2gp_1     | 		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
gp2gp_1     | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
gp2gp_1     | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
gp2gp_1     | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
gp2gp_1     | 		at java.base/java.lang.Thread.run(Unknown Source)
gp2gp_1     | 	Suppressed: java.lang.Exception: #block terminated with an error
gp2gp_1     | 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
gp2gp_1     | 		at reactor.core.publisher.Mono.block(Mono.java:1703)
gp2gp_1     | 		at uk.nhs.adaptors.gp2gp.mhs.MhsClient.sendEhrExtractCore(MhsClient.java:24)
gp2gp_1     | 		at uk.nhs.adaptors.gp2gp.ehr.SendEhrExtractCoreTaskExecutor.execute(SendEhrExtractCoreTaskExecutor.java:51)
gp2gp_1     | 		at uk.nhs.adaptors.gp2gp.ehr.SendEhrExtractCoreTaskExecutor.execute(SendEhrExtractCoreTaskExecutor.java:21)
gp2gp_1     | 		at uk.nhs.adaptors.gp2gp.common.task.TaskHandler.handle(TaskHandler.java:44)
gp2gp_1     | 		at uk.nhs.adaptors.gp2gp.common.task.TaskConsumer.receive(TaskConsumer.java:28)
gp2gp_1     | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gp2gp_1     | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
gp2gp_1     | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
gp2gp_1     | 		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
gp2gp_1     | 		at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
gp2gp_1     | 		at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
gp2gp_1     | 		at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
gp2gp_1     | 		at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
gp2gp_1     | 		at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
gp2gp_1     | 		at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
gp2gp_1     | 		at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
gp2gp_1     | 		at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
gp2gp_1     | 		at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
gp2gp_1     | 		at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
gp2gp_1     | 		at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
gp2gp_1     | 		at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
gp2gp_1     | 		at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by mattd-kainos** [comment]
Resolved with release 0.0.3. Please reopen if you still find any issues.
